# Generated by Django 3.1.7 on 2021-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='fairTrade.png', upload_to='Blog_images'),
        ),
    ]
