# Generated by Django 3.1.7 on 2021-02-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20210221_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='fairTrade.png', upload_to='Blog_images'),
        ),
    ]
